# Generated by Django 5.2.8 on 2025-11-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Physical MAC Address (e.g., 00:1A:2B:3C:4D:5E)', max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Current IP Address')),
                ('host_name', models.CharField(blank=True, help_text='Resolved Hostname', max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, help_text='Hardware Manufacturer (e.g., Apple, Espressif)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the device currently reachable?')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Timestamp of last successful ping')),
                ('alias', models.CharField(blank=True, help_text="User-friendly name (e.g., 'Dad's iPhone')", max_length=50, null=True)),
                ('is_trusted', models.BooleanField(default=False, help_text='If True, anomalies from this device are ignored')),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('devices_online', models.IntegerField(default=0)),
            ],
        ),
    ]
